CREATE TABLE categories_table (
    category_id BIGINT GENERATED ALWAYS AS IDENTITY,
    category_name TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE category_types_table (
    category_type_id BIGINT GENERATED ALWAYS AS IDENTITY,
    category_type_name TEXT PRIMARY KEY NOT NULL,
    category_name TEXT NOT NULL,
    FOREIGN KEY (category_name)
        REFERENCES categories_table(category_name)
);

CREATE TABLE plans_table (
    plan_id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    plan_name TEXT PRIMARY KEY NOT NULL,
    visibility_label TEXT NOT NULL,
    price_kes INTEGER NOT NULL,
    priority_rank INTEGER NOT NULL UNIQUE
);

CREATE TABLE plan_category_pricing (
    plan_name     TEXT NOT NULL REFERENCES plans_table(plan_name),
    category_name TEXT NOT NULL REFERENCES categories_table(category_name),
    price_kes     INTEGER NOT NULL,
    PRIMARY KEY (plan_name, category_name)
);

create table listings_table (
  listing_id bigint generated always as identity not null,
  listing_name text not null,
  listing_ward bigint not null,
  ward_location text null,
  location_url text null,
  listing_description jsonb null,
  listing_category text not null,
  category_type text not null,
  furnishing text null,
  rent_duration text null,
  phone_number text not null,
  price_kes integer not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null,
  plan_name text not null default 'Regular'::text,
  payment_status text not null default 'pending'::text,
  lister_uuid uuid not null,
  ward_display_name text null,
  constraint listings_table_pkey primary key (listing_id),
  constraint listings_table_category_type_fkey foreign KEY (category_type) references category_types_table (category_type_name),
  constraint listings_table_lister_uuid_fkey foreign KEY (lister_uuid) references users_table (lister_uuid),
  constraint listings_table_listing_category_fkey foreign KEY (listing_category) references categories_table (category_name),
  constraint listings_table_listing_ward_fkey foreign KEY (listing_ward) references wards_table (ward_id),
  constraint listings_table_plan_name_fkey foreign KEY (plan_name) references plans_table (plan_name)
);


create table payments_table (
  payment_id bigint generated by default as identity not null,
  lister_uuid uuid not null,
  listing_id bigint not null,
  plan_name text not null,
  checkout_request_id text null,
  mpesa_receipt text null,
  phone text null,
  amount_kes integer not null,
  status text not null default 'pending'::text,
  raw_callback jsonb null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null,
  constraint payments_table_pkey primary key (payment_id),
  constraint payments_table_lister_uuid_fkey foreign KEY (lister_uuid) references users_table (lister_uuid),
  constraint payments_table_listing_id_fkey foreign KEY (listing_id) references listings_table (listing_id),
  constraint payments_table_plan_name_fkey foreign KEY (plan_name) references plans_table (plan_name)
);


CREATE TABLE subscriptions_table (
    subscription_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    listing_id      BIGINT NOT NULL REFERENCES listings_table(listing_id),
    plan_name       TEXT NOT NULL REFERENCES plans_table(plan_name),
    payment_id      BIGINT NOT NULL REFERENCES payments_table(payment_id),
    status          TEXT NOT NULL DEFAULT 'active',
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT now()
);



create table public.images_table (
  media_id bigint generated always as identity not null,
  listing_id bigint not null,
  images_url jsonb null,
  video_url text null,
  constraint images_table_pkey primary key (media_id),
  constraint images_table_listing_id_key unique (listing_id),
  constraint images_table_listing_id_fkey foreign KEY (listing_id) references listings_table (listing_id)
) TABLESPACE pg_default;

create table public.users_table (
  lister_uuid uuid not null,
  username text null,
  lister_organization text null,
  lister_email text null,
  phone_number text null,
  ward_name text null,
  clerk_user_id text null,
  constraint users_table_pkey primary key (lister_uuid),
  constraint users_table_clerk_user_id_key unique (clerk_user_id),
  constraint users_table_ward_name_fkey foreign KEY (ward_name) references wards_table (ward_name)
) TABLESPACE pg_default;

CREATE TABLE listing_abandon_log (
    log_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    listing_id   BIGINT NOT NULL,
    plan_name_offered TEXT,
    reason       TEXT NOT NULL CHECK (reason IN ('rejected', 'timeout')),
    abandoned_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

create table if not exists public.auth_identity_map (
  mapping_id bigint generated always as identity primary key,
  legacy_user_id uuid not null,
  clerk_user_id text not null,
  legacy_username text,
  legacy_email text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  verified_at timestamptz,
  claimed_at timestamptz,
  updated_at timestamptz not null default now(),

  constraint auth_identity_map_legacy_user_unique
    unique (legacy_user_id),

  constraint auth_identity_map_clerk_user_unique
    unique (clerk_user_id),

  constraint auth_identity_map_status_check
    check (status in ('pending', 'active', 'revoked', 'needs_review'))
);

create index if not exists auth_identity_map_legacy_user_idx
  on public.auth_identity_map (legacy_user_id);

create index if not exists auth_identity_map_clerk_user_idx
  on public.auth_identity_map (clerk_user_id);
